/*
  PlayVerse Games - tournament.js

  Shared tournament state and timer helpers.

  IMPORTANT:
  - This file does NOT confirm payments.
  - This file does NOT unlock demo money.
  - This file does NOT determine real-money winners.
  - Browser localStorage is only used for non-trusted frontend state.
  - Real payment, balance, winner and withdrawal verification
    must be handled by a secure backend.

  Add this file to the root of the repository.

  To use it from an HTML page:

  <script src="tournament.js"></script>
*/

(function () {
    "use strict";

    const STORAGE_PREFIX = "playverse_";

    const TOURNAMENTS = {
        "2": {
            id: "2",
            name: "$2 Tournament",
            duration: 4 * 24 * 60 * 60 * 1000
        },

        "10": {
            id: "10",
            name: "$10 Challenge",
            duration: 3 * 24 * 60 * 60 * 1000
        },

        "15": {
            id: "15",
            name: "$15 Fast Challenge",
            duration: 24 * 60 * 60 * 1000
        }
    };


    function storageKey(name) {
        return STORAGE_PREFIX + name;
    }


    function getTournament(amount) {
        return TOURNAMENTS[String(amount)] || null;
    }


    function getEndTime(amount) {

        const tournament = getTournament(amount);

        if (!tournament) {
            return null;
        }

        const key =
            storageKey("tournament_end_" + tournament.id);

        const saved =
            localStorage.getItem(key);

        if (saved && Number.isFinite(Number(saved))) {
            return Number(saved);
        }

        const end =
            Date.now() + tournament.duration;

        localStorage.setItem(
            key,
            String(end)
        );

        return end;
    }


    function startTournament(amount) {

        const tournament = getTournament(amount);

        if (!tournament) {
            return null;
        }

        const key =
            storageKey("tournament_end_" + tournament.id);

        const end =
            Date.now() + tournament.duration;

        localStorage.setItem(
            key,
            String(end)
        );

        return end;
    }


    function resetTournament(amount) {

        const tournament = getTournament(amount);

        if (!tournament) {
            return null;
        }

        localStorage.removeItem(
            storageKey("tournament_end_" + tournament.id)
        );

        return getEndTime(amount);
    }


    function getRemaining(amount) {

        const end =
            getEndTime(amount);

        if (!end) {
            return 0;
        }

        return Math.max(
            0,
            end - Date.now()
        );
    }


    function isTournamentActive(amount) {
        return getRemaining(amount) > 0;
    }


    function formatTime(milliseconds) {

        const totalSeconds =
            Math.max(
                0,
                Math.floor(milliseconds / 1000)
            );

        const days =
            Math.floor(totalSeconds / 86400);

        const hours =
            Math.floor(
                (totalSeconds % 86400) / 3600
            );

        const minutes =
            Math.floor(
                (totalSeconds % 3600) / 60
            );

        const seconds =
            totalSeconds % 60;

        return (
            days + "d " +
            String(hours).padStart(2, "0") + "h " +
            String(minutes).padStart(2, "0") + "m " +
            String(seconds).padStart(2, "0") + "s"
        );
    }


    function getTimerText(amount) {

        const remaining =
            getRemaining(amount);

        if (remaining <= 0) {
            return "Tournament Ended";
        }

        return (
            "Tournament Ends In: " +
            formatTime(remaining)
        );
    }


    function generateWinnerCode() {

        return String(
            Math.floor(
                10000 +
                Math.random() * 90000
            )
        );
    }


    /*
      IMPORTANT:

      A real winner code must NOT be generated by this browser
      for a real-money withdrawal.

      The secure backend should determine the final leaderboard,
      select the winner, generate the official code, and store it
      server-side.

      This helper exists only for future backend integration and
      demo UI development.
    */

    function createDemoWinnerCode() {

        const existing =
            localStorage.getItem(
                storageKey("demo_winner_code")
            );

        if (existing) {
            return existing;
        }

        const code =
            generateWinnerCode();

        localStorage.setItem(
            storageKey("demo_winner_code"),
            code
        );

        return code;
    }


    function clearDemoWinnerCode() {

        localStorage.removeItem(
            storageKey("demo_winner_code")
        );

    }


    function getTournamentList() {
        return Object.values(TOURNAMENTS);
    }


    /*
      Optional automatic timer updater.

      Any element using:

        data-tournament-timer="2"

      will automatically display the $2 tournament countdown.

      Example:

        <div data-tournament-timer="2"></div>
    */

    function updateTimerElements() {

        const elements =
            document.querySelectorAll(
                "[data-tournament-timer]"
            );

        elements.forEach(function (element) {

            const amount =
                element.getAttribute(
                    "data-tournament-timer"
                );

            element.textContent =
                getTimerText(amount);

        });

    }


    function startTimerUpdater() {

        updateTimerElements();

        return setInterval(
            updateTimerElements,
            1000
        );

    }


    /*
      Frontend entry state.

      This is intentionally NOT payment confirmation.

      A production backend should replace this with a verified
      authenticated tournament status.
    */

    function getFrontendEntryState(amount) {

        const key =
            storageKey(
                "entry_status_" + String(amount)
            );

        return (
            localStorage.getItem(key) ||
            "PAYMENT NOT CONFIRMED"
        );

    }


    function setFrontendEntryState(amount, state) {

        /*
          This function is intentionally limited to UI state.
          It must never be used as proof of payment.
        */

        localStorage.setItem(
            storageKey(
                "entry_status_" + String(amount)
            ),
            String(state)
        );

    }


    /*
      Reset frontend tournament UI state.

      This does NOT reset any real-money account or backend
      tournament data.
    */

    function resetFrontendTournamentState(amount) {

        const id =
            String(amount);

        localStorage.removeItem(
            storageKey("entry_status_" + id)
        );

        localStorage.removeItem(
            storageKey("demo_winner_code")
        );

        localStorage.removeItem(
            storageKey("winner_status")
        );

        resetTournament(id);

    }


    /*
      Public API
    */

    window.PlayVerseTournament = {

        tournaments: TOURNAMENTS,

        getTournament,
        getTournamentList,

        getEndTime,
        startTournament,
        resetTournament,

        getRemaining,
        isTournamentActive,

        formatTime,
        getTimerText,

        generateWinnerCode,
        createDemoWinnerCode,
        clearDemoWinnerCode,

        getFrontendEntryState,
        setFrontendEntryState,

        resetFrontendTournamentState,

        updateTimerElements,
        startTimerUpdater
    };


    /*
      Automatically activate timer elements when the script loads.
    */

    if (
        document.readyState === "loading"
    ) {

        document.addEventListener(
            "DOMContentLoaded",
            startTimerUpdater
        );

    } else {

        startTimerUpdater();

    }

})();
